version: '3.9'
services:
  app:
    build:
      context: .
      target: dev
      dockerfile: .docker/app/Base.Dockerfile
    ports:
      - "8080:8080"
    restart: always
    # environment:
    #   - KRATOS_PUBLIC_URL=http://kratos:4433/
    #   - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - .:/app
    working_dir: "/app"
    command: ["sleep", "54000"]
    # command: ["go", "run", "."]

  redis:
    build:
      context: .docker/redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf
