// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/yunerou/oauth2-client/usecases/delivery/common_pages"
)

// Injectors from wire.go:

func initRoutesCollection() *routesCollection {
	commonPages := commonpages.NewCommonPages()
	serverRoutesCollection := NewroutesCollection(commonPages)
	return serverRoutesCollection
}
