// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cli

import (
	"github.com/yunerou/oauth2-client/app_entry/cli/jobs/example"
)

// Injectors from wire.go:

func initJobsCollection() *jobsCollection {
	jobsCmd := example.NewJobsCmd()
	cliJobsCollection := NewJobsCollection(jobsCmd)
	return cliJobsCollection
}
